name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write     
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-amd64
          - os: windows-latest
            suffix: windows-amd64
          - os: macos-latest
            suffix: macos-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Extract Cargo Metadata
        shell: bash
        run: |
          RAW_METADATA=$(cargo metadata --no-deps --format-version 1)
          PROJECT_NAME=$(echo $RAW_METADATA | jq -r '.packages[0].name')
          PROJECT_VERSION=$(echo $RAW_METADATA | jq -r '.packages[0].version')
          
          echo "BINARY_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          
      - name: Build
        run: cargo build --release

      - name: Archive artifacts
        shell: bash
        run: |
          ASSET_NAME="${{ env.BINARY_NAME }}-${{ matrix.suffix }}"
          
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            powershell Compress-Archive -Path "target/release/${{ env.BINARY_NAME }}.exe" -DestinationPath "${ASSET_NAME}.zip"
          else
            tar -czvf "${ASSET_NAME}.tar.gz" -C target/release "${{ env.BINARY_NAME }}"
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PROJECT_VERSION }}
          name: Release v${{ env.PROJECT_VERSION }}
          draft: true
          fail_on_unmatched_files: false
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
