name: Release Checks
on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-verify:
    name: Verify on ${{ matrix.suffix }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-amd64
          - os: windows-latest
            suffix: windows-amd64
          - os: macos-latest
            suffix: macos-arm64
            target: aarch64-apple-darwin
          - os: macos-latest
            suffix: macos-intel-amd64
            target: x86_64-apple-darwin
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужно для доступа к тегам

      - name: Check version uniqueness
        if: matrix.os == 'ubuntu-latest' # Проверяем один раз на Linux, чтобы не дублировать
        shell: bash
        run: |
          CURRENT_VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d '"' -f 2)
          TAG_NAME="v$CURRENT_VERSION"
          
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "❌ ERROR: Release $TAG_NAME already exists."
            echo "Change project version in Cargo.toml"
            exit 1
          fi

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: ${{ matrix.target }} # Устанавливаем нужный таргет для Mac

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-build-${{ matrix.os }}"
          
      - name: Run Tests
        # Запускаем тесты только если архитектура совпадает с хостом (не кросс-сборка)
        # На Mac Intel (cross) тесты лучше пропустить, так как они не запустятся на M1
        if: matrix.target != 'x86_64-apple-darwin'
        run: cargo test

#      - name: Lint Code
#        run: cargo clippy -- -D warnings

      - name: Check Release Build
        shell: bash
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo check --release --target ${{ matrix.target }}
          else
            cargo check --release
          fi
