name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build for ${{ matrix.suffix }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-amd64
          - os: windows-latest
            suffix: windows-amd64
          - os: macos-latest
            suffix: macos-arm64
            target: aarch64-apple-darwin
          - os: macos-latest
            suffix: macos-intel-amd64
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }} # для кросс-сборки на Mac

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-build-${{ matrix.os }}"
          
      - name: Extract Cargo Metadata
        shell: bash
        run: |
          RAW_METADATA=$(cargo metadata --no-deps --format-version 1)
          PROJECT_NAME=$(echo $RAW_METADATA | jq -r '.packages[0].name')
          PROJECT_VERSION=$(echo $RAW_METADATA | jq -r '.packages[0].version')
          
          echo "BINARY_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          
      - name: Build
        shell: bash
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --release
          fi

      - name: Archive artifacts
        shell: bash
        run: |
          BINARY_NAME="${{ env.BINARY_NAME }}"
          ASSET_NAME="${BINARY_NAME}-${{ matrix.suffix }}"
          
          if [ -n "${{ matrix.target }}" ]; then
            BIN_PATH="target/${{ matrix.target }}/release/${BINARY_NAME}"
          else
            BIN_PATH="target/release/${BINARY_NAME}"
          fi

          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            powershell Compress-Archive -Path "${BIN_PATH}.exe" -DestinationPath "${ASSET_NAME}.zip"
          else
            tar -czvf "${ASSET_NAME}.tar.gz" -C "$(dirname $BIN_PATH)" "${BINARY_NAME}"
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PROJECT_VERSION }}
          name: v${{ env.PROJECT_VERSION }}
          draft: true
          fail_on_unmatched_files: false
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
